// imageurl.tsx
export interface ImageResource {
  id: string;
  url: any;
  info: string;
  title : string;
}

const imageUrls: ImageResource[] = [
  { id: '1', url: require('../assets/images/7698215_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2016                                                                  Eğlenceli ve neşeli kuzucuğun merak uyandıran hikayesi minik dostlarımızla buluşuyor. Heyecan dolu bu hikayeye sen de katıl!   ', title:'KUZUCUK' },
  { id: '2', url: require('../assets/images/7698939_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2013                                                                  Cille, hayal gücü geniş minik izleyicilerin dünyasına adım atıyor. Cillenin eğlenceli maceraları, dostluk ve paylaşmanın önemini vurgularken, her bölümde yeni sürprizlerle dolu. Haydi, bu neşeli dünyaya sen de katıl!', title:'CİLLE'},
  { id: '3', url: require('../assets/images/7700364_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2015                                                                  İki sıkı dostun maceraları seni kahkahalara boğacak! Dostluğun, yardımlaşmanın ve paylaşmanın ön planda olduğu bu eğlenceli serüvende, küçük dostlarımız yeni şeyler öğrenmeye devam ediyor.', title:'BİZ İKİMİZ'},
  { id: '4', url: require('../assets/images/7700469_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2012                                                                  Yer altında yaşayan sevimli köstebek ailesinin komik ve macera dolu dünyasına adım at! Her bölümde eğlence ve öğretici olaylarla dolu bu dizi, minik dostlarımız için keyifli bir yolculuk sunuyor.', title:'KÖSTEBEKGİLLER'},
  { id: '5', url: require('../assets/images/7700505_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2011                                                                  Kuklaların sihirli dünyasında yer almak ister misin? Renkli karakterlerle dolu bu tiyatro, eğitici ve eğlenceli hikayeleriyle çocuklara keyifli dakikalar yaşatıyor.', title:'KUKLA TİYATROSU'},
  { id: '6', url: require('../assets/images/7701292_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2017                                                                  Elif ve sevimli arkadaşları, her bölümde yeni maceralar keşfediyor! Eğitici ve öğretici hikayelerle dolu bu seride, küçük izleyiciler dostluk, paylaşma ve yardımlaşma üzerine dersler öğreniyor.', title:'ELİF ve ARKADAŞLARI'},
  { id: '7', url: require('../assets/images/7701338_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2015                                                                   Leylek kardeşin göç yolculuğunda yaşadığı eğlenceli ve öğretici maceralar, çocuklara doğayı ve hayvanları sevdiriyor. Heyecan dolu bu hikayeye sen de katıl!', title:'LEYLEK KARDEŞ' },
  { id: '8', url: require('../assets/images/7701360_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2016                                                                  Hayal gücünün sınırlarını zorlayan bu dizi, minik izleyicilere "Ben olsaydım ne yapardım?" sorusunu sorduruyor. Her bölümde farklı bir karakterin yerine geçerek hayal kurmak ve öğrenmek mümkün!', title:'OLSAYDIM'},
  { id: '9', url: require('../assets/images/7701777_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2017                                                                  Sayılarla dolu bu büyülü dünyada, matematiği keşfetmek hiç bu kadar eğlenceli olmamıştı! Çocuklar, her bölümde eğlenceli ve öğretici bulmacalarla karşılaşarak matematikle tanışıyor.', title:'SİHİRLİ MATEMATİK'},
  { id: '10', url: require('../assets/images/7701944_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2019                                                                 Kuklaların gizemli köşkünde sırlarla dolu bir yolculuğa çık! Kuklaların komik ve eğlenceli dünyası, çocuklara hayal gücüyle dolu maceralar sunuyor.', title:'KUKLALI KÖŞK'},
  { id: '11', url: require('../assets/images/7703674_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2018                                                                 Elif’in hayal dünyasında keşfe çıkmaya hazır mısın? Her bölümde Elif’in renkli hayal gücüne konuk ol ve onun düş dünyasındaki eğlenceli ve öğretici maceralara katıl.', title:'ELİF"İN DÜŞLERİ'},
  { id: '12', url: require('../assets/images/7703679_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2013                                                                  İbi ve arkadaşları, birbirinden ilginç ve eğlenceli bulmacaları çözerek maceradan maceraya atılıyor. Eğitici ve öğretici bu dizi, çocuklara keşfetmenin ve öğrenmenin ne kadar keyifli olabileceğini gösteriyor.', title:'İBİ' },
  { id: '13', url: require('../assets/images/7706751_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2017                                                                 Pırıl ve arkadaşlarıyla sayılar ve şekillerin büyülü dünyasına yolculuk yap! Matematiği eğlenceli hale getiren bu dizi, çocukların öğrenme sürecini keyifli hale getiriyor.', title:'PIRIL'},
  { id: '14', url: require('../assets/images/7706996_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2018                                                                 Meraklı Aslan, icatlarla dolu dünyasında eğlenceli maceralar peşinde! Teknoloji ve bilimle ilgilenen minik izleyiciler için ilham verici bu dizi, öğrenmeyi teşvik ediyor.', title:'ASLAN'},
  { id: '15', url: require('../assets/images/7707133_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2014                                                                 Tarihin derinliklerine yolculuk yapan Küçük Hezarfen, geçmişin büyük buluşlarını ve mucitlerini keşfediyor. Bu eğitici ve öğretici dizi, bilim ve tarihe merak uyandırıyor.', title:'KÜÇÜK HEZARFEN'},
  { id: '16', url: require('../assets/images/7707740_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2013                                                                 Akıllı tavşan Momo, zeki ve hızlı çözümleriyle ormandaki arkadaşlarına yardım ediyor! Merak uyandıran bilmecelerle dolu bu eğitici seride, çocuklar mantık ve problem çözme becerilerini geliştiriyor.', title:'AKILLI TAVŞAN MOMO'},
  { id: '17', url: require('../assets/images/7707969_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2015                                                                 Bizim Diyar"da birbirinden farklı hayvan karakterler, eğitici ve eğlenceli maceralar yaşıyor. Paylaşım, dostluk ve yardımlaşma temalarının işlendiği bu dizi, çocuklara değerli yaşam dersleri veriyor.', title:'BİZİM DİYAR'},
  { id: '18', url: require('../assets/images/7709145_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2016                                                                 Her bölümde farklı bir sürprizin ortaya çıktığı bu eğlenceli dizi, çocukların hayal güçlerini geliştirmelerine yardımcı oluyor. Sürprizlerle dolu bu dünyada, öğrenmek ve eğlenmek bir arada.', title:'SÜRPRİZ KUTUSU'},
  { id: '19', url: require('../assets/images/7710575_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2016                                                                 Tarım ve doğayı keşfetmeye ne dersin? Kimin Tarlası"nda, çocuklar çiftçilik ve doğa hakkında eğitici bilgiler öğrenirken, eğlenceli maceralara katılıyor.', title:'KİMİN TARLASI'},
  { id: '20', url: require('../assets/images/7710644_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2013                                                                 Renkli ve ilginç bir dünya olan 64 Kare Ülkesi"nde, her bölümde farklı karakterlerle karşılaş ve bulmacaları çöz! Eğlenceli hikayelerle dolu bu dizi, çocukları düşünmeye ve öğrenmeye teşvik ediyor.', title:'64 KARE ÜLKESİ'},
  { id: '21', url: require('../assets/images/7710964_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2015                                                                 Kare ve arkadaşları, şekillerin dünyasında eğlenceli ve öğretici maceralar yaşıyor! Sayılar ve şekilleri öğrenmeyi keyifli hale getiren bu dizi, çocukların matematiksel düşünme becerilerini geliştirmeyi hedefliyor.', title:'KARE'},
  { id: '22', url: require('../assets/images/7711356_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2006                                                                  Geleneksel masal kahramanı Keloğlan, zeki ve neşeli kişiliğiyle yeni neslin favorisi oluyor. Her bölümde dostlarıyla maceradan maceraya koşan Keloğlan, izleyicilere iyilik ve yardımlaşma gibi değerleri aşılıyor.' , title:'KELOĞLAN'},
  { id: '23', url: require('../assets/images/7712208_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2018                                                                  Sevimli dodo kuşu ve arkadaşları, birbirinden renkli ve eğlenceli maceralar yaşıyor. Dodohando"nun büyülü dünyasında dostluk, dayanışma ve eğlence bir arada!' , title:'DODOHANDO'},
  { id: '24', url: require('../assets/images/7712481_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2014                                                                  Bozkırda geçen bu sıcak hikayede Maysa ve sadık atı Bulut"un dostluğu ve maceraları anlatılıyor. Geleneksel kültürel motiflerle dolu bu dizi, çocuklara doğayla iç içe bir yaşamı keşfetme fırsatı sunuyor.', title:'MAYSA ve BULUT' },
  { id: '25', url: require('../assets/images/7712599_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2018                                                                  Mutlu Oyuncak Dükkanı"nda her oyuncak, kendi hikayesini anlatıyor! Çocukların hayal gücünü geliştiren bu renkli dünyada, paylaşmanın ve arkadaşlığın önemi vurgulanıyor.' , title:'MUTLU OYUNCAK DÜKKANI'},
  { id: '26', url: require('../assets/images/7712705_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2017                                                                  Küçük at Doru"nun, çiftlikteki eğlenceli ve öğretici maceraları minik izleyicileriyle buluşuyor. Dostluk, dayanışma ve sorumluluk temalarını işleyen bu dizi, çocuklar için hem öğretici hem de eğlenceli bir deneyim sunuyor.', title:'DORU' },
  { id: '27', url: require('../assets/images/7712845_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2019                                                                  Nasreddin Hoca, zaman içinde yolculuk yaparak çocuklara tarih, mizah ve yaşam dersleri veriyor. Bu eğlenceli ve öğretici dizi, çocuklara geçmişle günümüz arasında bağ kurma fırsatı sunuyor.' , title:'NASREDDİN HOCA ZAMAN YOLCUSU'},
  { id: '28', url: require('../assets/images/7712978_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2017                                                                  Suyun önemi ve çevre bilinci üzerine kurulu bu seride, su elçileri çocuklara su tasarrufu ve doğayı koruma üzerine eğitici bilgiler veriyor. Her bölümde çevre dostu çözümler ve hikayeler anlatılıyor.', title:'SU ELÇİLERİ' },
  { id: '29', url: require('../assets/images/7713061_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2020                                                                  Erdem, çocuklara ahlaki değerler ve doğru davranışlar üzerine hikayeler sunuyor. Ahlak ve erdem temalarının işlendiği bu dizi, izleyicilere ders çıkaracakları hikayelerle dolu.' , title:'ERDEM'},
  { id: '30', url: require('../assets/images/7713165_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2019                                                                 Ozi, azim ve cesaret dolu maceralarıyla dikkat çekiyor. Engelleri aşan bu özel kahraman, izleyicilere kararlılık ve kendine güven üzerine ilham verici mesajlar sunuyor.', title:'OZİ'},
  { id: '31', url: require('../assets/images/7713317_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2017                                                                 Patapata"nın eğlenceli dünyasına adım at! Her bölümde hızlı ve macera dolu olaylarla karşılaşan kahramanlarımız, çocuklara eğlenceli ve öğretici hikayeler sunuyor.', title:'PATAPATA'},
  { id: '32', url: require('../assets/images/7713648_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2016                                                                 Meraklı Ege ve onun sevimli kuş arkadaşı Gaga, doğanın gizemlerini keşfediyor! Her bölümde yeni bilgiler öğrenen ikili, çocuklara doğayı sevmeyi ve korumayı aşılıyor.', title:'EGE ile GAGA'},
  { id: '33', url: require('../assets/images/7713995_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2012                                                                 Sevimli dinozor Pırdino"nun maceraları, zaman yolculuğu ve eğlenceli olaylarla dolu! Çocuklar, Pırdino’nun hikayeleriyle geçmişten günümüze gelen dostluğa ve maceraya tanık oluyor.', title:'PIRDİNO'},
  { id: '34', url: require('../assets/images/7714418_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2019                                                                  Ramazan ayının manevi atmosferinde, çocuklara Ramazan geleneklerini anlatan bu seri, eğitici ve değer dolu hikayeler sunuyor. Her bölümde çocuklar, paylaşmanın ve sabrın önemini öğreniyor.', title:'RAMAZAN GÜNCESİ' },
  { id: '35', url: require('../assets/images/18323212_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2018                                                                 Minik muhabirler iş başında! Çocuklar için özel olarak hazırlanan bu haber programı, onların anlayabileceği dille dünya olaylarını ve ilginç konuları eğlenceli bir şekilde sunuyor.' , title:'HABERİN OLSUN'},
  { id: '36', url: require('../assets/images/7714748_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2015                                                                  Ormanın çılgın sakinleriyle tanış! Eğlenceli ve komik olaylarla dolu bu seride, çocuklar doğanın güzelliklerini keşfederken kahkaha dolu anlar yaşıyor.' , title:'ÇILGIN ORMAN'},
  { id: '37', url: require('../assets/images/7714841_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2020                                                                  Ramazan davulcusu ve sadık köpeği, her gece mahalleyi neşeyle uyandırıyor. Bu sıcak ve komik hikayede, Ramazan’ın geleneksel ruhu çocuklara eğlenceli bir şekilde anlatılıyor.' , title:'RAMAZAN DAVULCUSU VE KÖPEĞİ'},
  { id: '38', url: require('../assets/images/7719031_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2017                                                                  Klasik masalları modern bir dille anlatan bu dizi, çocukları hayal dünyasında keyifli bir yolculuğa çıkarıyor. Her bölümde farklı bir masal kahramanıyla tanışan çocuklar, eğlenceli ve öğretici dersler alıyor.', title:'MASAL KİTABI' },
  { id: '39', url: require('../assets/images/7719106_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2018                                                                  Merak uyandıran sorulara eğlenceli ve öğretici cevaplar veren bu dizi, çocukların öğrenme hevesini artırıyor. Her bölümde "Nasıl acaba?" sorusuyla farklı konular keşfediliyor.' , title:'NASIL ACABA'},
  { id: '40', url: require('../assets/images/7719475_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2019                                                                  Pak ve uçan arkadaşı Pırpır, farklı dünyalarda eğlenceli ve öğretici maceralar yaşıyor. Çocuklara dostluk, yardımseverlik ve öğrenmenin önemini aşılayan bu seri, keyifli bir deneyim sunuyor.', title:'PAK İLE PIRPIR' },
  { id: '41', url: require('../assets/images/7719537_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2019                                                                  Oyun oynamak hiç bu kadar eğlenceli olmamıştı! Bu seride, çocuklar eğitici oyunlar ve etkinliklerle dolu bir dünyaya adım atıyor. Hem eğlen hem öğren!' , title:'OYUNDAYIM'},
  { id: '42', url: require('../assets/images/7719649_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2019                                                                  Sevgi dolu öğretmenlerin çocuklar üzerindeki etkilerini anlatan bu dizi, öğretmen ve öğrenci arasındaki bağı vurguluyor. Her bölümde farklı bir öğretmen ve öğrencinin hikayesi anlatılıyor, eğlenceli ve öğretici anılar canlanıyor.', title:'ÖĞRETMENİM CANIM BENİM' },
  { id: '43', url: require('../assets/images/7719819.jpeg') ,info: '●Yayın Yılı: 2021                                                                               Ramazan Tayfa, Ramazan ayının coşkusunu ve maneviyatını çocuklara eğlenceli bir dille anlatıyor. Çocuklar, Tayfa ile birlikte oruç tutmanın, yardımlaşmanın ve paylaşmanın güzelliklerini keşfediyor', title:'RAMAZAN TAYFA'},
  { id: '44', url: require('../assets/images/7720176_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2020                                                                 Yade Yade, günlük yaşamdan eğlenceli ve düşündürücü hikayelerle çocuklara farklı bakış açıları kazandırıyor. Meraklı ve enerjik Yade’nin maceraları, çocuklara hem eğlence hem de öğreti sunuyor.', title:'YADE YADE'},
  { id: '45', url: require('../assets/images/7720579_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2012                                                                 Küçük kardeşler Müge ve Mine’nin günlük yaşamlarını ve hayal dünyalarını konu alan bu dizi, kardeş sevgisini ve aile bağlarını işliyor. Sevimli karakterlerle dolu bu eğlenceli seride, çocuklar kardeş olmanın güzelliklerini keşfediyor.', title:'CANIM KARDEŞİM'},
  { id: '46', url: require('../assets/images/7890752_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2018                                                                 Görmenin sadece gözlerle değil, kalple ve akılla da mümkün olduğunu anlatan bu dizi, çocuklara farklı bakış açıları kazandırmayı hedefliyor. Her bölümde keşfedilmeyi bekleyen güzellikler gözler önüne seriliyor.', title:'GÖRMEK GEREK'},
  { id: '47', url: require('../assets/images/7935041_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2014                                                                  Sevimli Niloya, ailesi ve arkadaşlarıyla doğada eğlenceli maceralar yaşıyor. Şarkılarla dolu bu dizi, çocuklara arkadaşlık, paylaşım ve doğa sevgisini aşılıyor.', title:'NİLOYA' },
  { id: '48', url: require('../assets/images/8021691.jpeg') ,info: '●Yayın Yılı: 2014                                                                               Mahallenin neşeli tayfası, eğlenceli maceraları ve sıcak dostluklarıyla çocukların kalbinde yer ediyor. Her bölümde Rafadan Tayfa"nın maceralarıyla dolu eğlenceli hikayeler işleniyor.', title:'RAFADAN TAYFA'},
  { id: '49', url: require('../assets/images/8492014_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2020                                                                 Müziğin evrensel diliyle çocuklara farklı kültürlerin melodilerini tanıtan bu dizi, eğlenceli ve öğretici müzik dersleri sunuyor. Çocuklar, her bölümde müziğin büyülü dünyasına adım atıyor.', title:'MÜZİK'},
  { id: '50', url: require('../assets/images/8495657_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2017                                                                 Denizlerin derinliklerinde geçen bu dizi, çocuklara deniz canlılarının yaşamlarını ve doğanın güzelliklerini keşfetme fırsatı sunuyor. Mavi Dünya, çevre bilincini artırmayı amaçlayan bir macera sunuyor.', title:'MAVİ DÜNYA'},
  { id: '51', url: require('../assets/images/9028606_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2018                                                                 Süper kahraman olmadan da iyilik yapılabileceğini anlatan bu dizi, çocuklara cesaret, dostluk ve sorumluluk kavramlarını öğretirken, heyecan dolu maceralar sunuyor.', title:'TOZKOPARAN'},
  { id: '52', url: require('../assets/images/9042905.jpeg'),info: '●Yayın Yılı: 2019                                                                                Trafik kurallarını eğlenceli ve öğretici bir şekilde işleyen bu dizi, çocuklara trafik güvenliği hakkında bilgi veriyor. Her bölümde Trafik Tayfa, eğlenceli bir olay üzerinden kuralları anlatıyor.' , title:'TRAFİK TAYFA'},
  { id: '53', url: require('../assets/images/9240929.jpeg'),info: '●Yayın Yılı: 2017                                                                                Çevre dostu Kaptan Pengu ve ekibi, doğayı korumak için maceradan maceraya atılıyor. Çocuklara çevre bilinci kazandıran bu dizi, eğlenceli ve öğretici bir içerik sunuyor.' , title:'KAPTAN PENGU'},
  { id: '54', url: require('../assets/images/9258564_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2016                                                                 Geçmişe yolculuk yapan Emiray, tarihin önemli olaylarını keşfederken eğitici ve macera dolu anlar yaşıyor. Çocuklar, Emiray’ın maceralarıyla tarihi öğreniyor ve değerli bilgiler ediniyor.', title:'EMİRAY'},
  { id: '55', url: require('../assets/images/9800932.jpeg') ,info: '●Yayın Yılı: 2018                                                                               Gizemli Bulmaca Kulesi"nde her bölümde çözülmesi gereken yeni bir bulmaca var! Çocuklar, eğlenceli karakterlerle birlikte bulmacaları çözerken, problem çözme becerilerini geliştiriyor.', title:'BULMACA KULESİ'},
  { id: '56', url: require('../assets/images/9860770.jpeg') ,info: '●Yayın Yılı: 2020                                                                               Dijital dünyanın kapılarını aralayan bu dizi, teknoloji ve internet kullanımı hakkında çocuklara önemli bilgiler veriyor. Dijital Tayfa, teknolojiye eğlenceli ve öğretici bir bakış sunuyor.', title:'DİJİTAL TAYFA'},
  { id: '57', url: require('../assets/images/10165450_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2018                                                                Z Takımı, eğlenceli ve macera dolu olaylarla dolu hikayeleriyle izleyicilerin karşısına çıkıyor. Çocuklar, takım ruhunu ve birlikte çalışmanın önemini öğreniyor.', title:'Z TAKIMI'},
  { id: '58', url: require('../assets/images/11021453_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2021                                                                 Efsanelerle dolu Kız Kulesi, her bölümde farklı bir masalı çocuklarla buluşturuyor. Bu seride çocuklar, tarihî ve kültürel değerlerle dolu masalları keşfediyor.' , title:'KIZ KULESİ MASALLARI'},
  { id: '59', url: require('../assets/images/13135662_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2020                                                                 Variloto, sürükleyici yarışlar ve heyecan dolu maceralarla dolu bir dizi. Çocuklar, Variloto ile birlikte hız ve rekabetin keyfini çıkarırken, eğlenceli anlar yaşıyor.' , title:'VARİLOTO'},
  { id: '60', url: require('../assets/images/13761904_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2018                                                                Yusuf"un hikayeleriyle dolu bu dizi, çocuklara değerli öğretiler sunuyor. Aile bağları, yardımlaşma ve ahlak gibi konuların işlendiği Yusufname, çocuklara eğlenceli ve anlamlı bir içerik sunuyor.', title:'YUSUFNAME'},
  { id: '61', url: require('../assets/images/14445100_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2022                                                                Aybek, bilime ve uzaya ilgi duyan bir çocuğun heyecan verici maceralarını konu alıyor. Aybek’in keşif yolculuğunda, bilimsel kavramlar eğlenceli bir dille anlatılıyor, çocuklar uzayla ilgili birçok yeni bilgi öğreniyor.', title:'AYBEK'},
  { id: '62', url: require('../assets/images/14462997_0-0-852-1279.jpeg'),info: '●Yayın Yılı: 2021                                                                  Ser-a, uzak bir gelecekte geçen ve teknolojinin etkisiyle şekillenen bir dünyayı keşfetmeye çalışan kahramanların hikayesini anlatıyor. Serinin her bölümü, çocuklara bilim kurgu ve macera dolu bir dünya sunuyor.', title:'SER-a' },
  { id: '63', url: require('../assets/images/14471421_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2020                                                                 Babasıyla maceradan maceraya atılan bir çocuğun hikayesini konu alan bu dizi, aile ilişkilerini ve birlikte geçirilen zamanın değerini ön plana çıkarıyor.', title:'BABAMIN GÖLGESİ' },
  { id: '64', url: require('../assets/images/14520702_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2021                                                                 Mistik bir dünyanın kapılarını aralayan bu dizi, kahraman Sagun’un fantastik maceralarını anlatıyor. Her bölümde yeni bir serüvene atılan Sagun, izleyicilere hayal gücünün sınırlarını zorluyor.' , title:'SAGUN'},
  { id: '65', url: require('../assets/images/14520721_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2019                                                                 Kehribar ve Boncuk adında iki sevimli karakterin dostluk dolu maceralarını konu alan bu dizi, arkadaşlık, yardımlaşma ve paylaşma temalarını işliyor. Eğlenceli ve öğretici hikayeleriyle çocukların kalbini kazanıyor.', title:'KEHRİBAR ile BONCUK' },
  { id: '66', url: require('../assets/images/14943845_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2022                                                                 Teknolojinin hızla geliştiği dünyada, Ekip Siberay dijital güvenlik ve internet kullanımı hakkında çocuklara eğlenceli bir dille bilgi veriyor. Siber güvenliğin önemini anlatan bu dizi, çocuklara teknolojiyi güvenli kullanma bilinci kazandırıyor.', title:'Ekip: SİBERAY' },
  { id: '67', url: require('../assets/images/15369862_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2020                                                                Türkçenin zenginliklerini ve dilin gücünü keşfetmeye hazır mısınız? Türkçe Benim Evim, dilimizi sevdirmeyi amaçlayan eğitici ve eğlenceli bir dizi. Her bölümde Türkçe ile ilgili yeni bilgiler öğreniyoruz.', title:'TÜRKÇE BENİM EVİM'},
  { id: '68', url: require('../assets/images/15438661_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2016                                                                Rüzgar Gülü, eğlenceli ve renkli bir dünyada geçen maceraları konu alıyor. Çocuklar, doğanın güzelliklerini keşfederken, aynı zamanda çevre bilinci kazanıyor.', title:'RÜZGAR GÜLÜ'},
  { id: '69', url: require('../assets/images/15439397_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2021                                                                Çocukların günlük yaşantılarından esinlenilen bu dizi, her bölümde farklı bir macera sunuyor. Çocukların gözünden dünyayı anlatan Çocukçuf, samimi ve eğlenceli bir bakış açısı sunuyor.', title:'ÇOCUKÇUF'},
  { id: '70', url: require('../assets/images/15439404_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2022                                                                Reptır, robotik ve teknoloji temalı bir dizi olup, çocukları teknolojinin heyecan verici dünyasına götürüyor. Her bölümde yeni bir keşif ve robotların hayatımıza nasıl entegre olabileceğini öğreniyoruz.', title:'REPTIR'},
  { id: '71', url: require('../assets/images/15500174_0-0-2119-3178.jpeg') ,info: '●Yayın Yılı: 2021                                                                Zeka ve strateji üzerine kurulu bu dizi, çocuklara problem çözme yeteneklerini geliştirmeleri için fırsatlar sunuyor. Her bölümde çocuklar yeni bir bulmaca veya zorlukla karşılaşıyor.', title:'TAKTİK 6'},
  { id: '72', url: require('../assets/images/16240917_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2020                                                                 Kuklaların eğlenceli dünyasında geçen bu dizi, her bölümde farklı bir hikaye sunuyor. Kuklalar, çocuklara eğlenceli ve öğretici maceralar yaşatıyor.' , title:'KUKLA STÜDYOSU'},
  { id: '73', url: require('../assets/images/17115207_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2022                                                                 İbi’nin galaktik maceralarını konu alan bu seri, çocukları uzayın derinliklerinde sürükleyici bir yolculuğa çıkarıyor. Her bölümde yeni bir gezegen keşfediliyor ve bilimsel bilgiler eğlenceli bir şekilde işleniyor.' , title:'İBİ GALAKTİK SERÜVEN'},
  { id: '74', url: require('../assets/images/17201505_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2019                                                                 Aslan, bilimsel deneylerle dolu odasında çocuklara eğlenceli ve öğretici deneyler sunuyor. Çocuklar, Aslan’ın maceralarıyla bilim dünyasını keşfederken, deney yapmayı öğreniyor.' , title:'ASLAN"IN DENEY ODASI'},
  { id: '75', url: require('../assets/images/18144890_0-0-2119-3178.jpeg'),info: '●Yayın Yılı: 2021                                                                 Çocukların hayal dünyasına hitap eden bu dizi, oyunlarla dolu renkli bir evrende geçiyor. Her bölümde yeni bir oyun dünyası keşfediliyor, çocuklar eğlenirken öğreniyor.' , title:'OYUN DÜNYASI'},

];

/**
 * Verileri gruplara ayıran fonksiyon.
 * @param data - Görsel verileri.
 * @param groupSize - Her gruptaki eleman sayısı.
 * @returns Gruplandırılmış veri.
 */
export function groupImageUrls(data: ImageResource[], groupSize: number) {
  const grouped: { id: string; data: ImageResource[] }[] = [];
  
  for (let i = 0; i < data.length; i += groupSize) {
    grouped.push({
      id: (i / groupSize + 1).toString(),
      data: data.slice(i, i + groupSize),
    });
  }
  
  return grouped;
}

export { imageUrls };
